// <auto-generated />
using Dasa.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(ScraperDbContext))]
    [Migration("20200218175701_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Dasa.Data.Tables.BuscaConsolidada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(50);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.Property<bool>("MaiorPreco")
                        .HasColumnType("int");

                    b.Property<bool>("MenorPreco")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(50);

                    b.Property<decimal>("Preco")
                        .HasColumnType("real");

                    b.Property<int>("PrecoOrdenacao")
                        .HasColumnType("int");

                    b.Property<bool>("ProdutoNovo")
                        .HasColumnType("int");

                    b.Property<string>("Tamanhos")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.Property<string>("UrlProduto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("BuscaConsolidada");
                });

            modelBuilder.Entity("Dasa.Data.Tables.RegistroBusca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataHora")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(50);

                    b.Property<string>("NomeSiteOrigem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("RegistroBusca");
                });

            modelBuilder.Entity("Dasa.Data.Tables.Roupas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuscaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(50);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.Property<decimal>("Preco")
                        .HasColumnType("real");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.Property<string>("UrlProduto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("BuscaId");

                    b.ToTable("Roupas");
                });

            modelBuilder.Entity("Dasa.Data.Tables.RoupasTamanho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoupaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("RoupaId");

                    b.ToTable("RoupasTamanho");
                });

            modelBuilder.Entity("Dasa.Data.Tables.Roupas", b =>
                {
                    b.HasOne("Dasa.Data.Tables.RegistroBusca", null)
                        .WithMany("Roupas")
                        .HasForeignKey("BuscaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dasa.Data.Tables.RoupasTamanho", b =>
                {
                    b.HasOne("Dasa.Data.Tables.Roupas", null)
                        .WithMany("Tamanhos")
                        .HasForeignKey("RoupaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
